[package]
name = "fs"
description = "Handles file system operations."
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
model = { path = "../model" }
serde = { workspace = true }
